name: Deploy static content to Pages

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Clean node modules and dist
        run: |
          rm -rf node_modules
          rm -rf dist

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
      
      # Uncomment this if you need a custom domain in the future
      # - name: Create CNAME file
      # run: echo "www.lepiaje.com" > ./dist/CNAME
        
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist